version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
clone_depth: 1
branches:
  only:
    - master
    - develop
environment:
 global:
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
   DOTNET_CLI_TELEMETRY_OPTOUT: 1
# Deploy to GitHub Releases
- provider: GitHub
  artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  release: $(appveyor_build_version)
  draft: true
  prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true
      